export const ThemeColors = {
  dark: {
    background: "#000",
    surface: "rgba(34, 34, 34, 0.6)",
    surfaceSolid: "#222",
    /** Nested panels inside cards/modals (chart boxes, etc.) */
    surfaceInset: "#2C2C2C",
    border: "#333",
    text: "#fff",
    textSecondary: "#bbb",
    textMuted: "#aaa",
    /** Faded input placeholders (world-record hints, etc.) */
    placeholder: "#666",
    inputBackground: "#333",
    inputText: "#fff",
    inputBorder: "#444",
    buttonPrimary: "#D35400",
    buttonSecondary: "#444",
    buttonText: "#fff",
    cardBackground: "#111",
    modalOverlay: "rgba(0, 0, 0, 0.8)",
    statusBar: "light-content",
  },
  light: {
    // Slightly deeper page gray so white surfaces and Liquid Glass read apart.
    background: "#DADBDF",
    surface: "#FFFFFF",
    surfaceSolid: "#FFFFFF",
    /** Nested panels inside cards/modals — visible against white like dark mode */
    surfaceInset: "#E8E8ED",
    border: "#6E6E73",
    text: "#111113",
    textSecondary: "#3A3A3C",
    textMuted: "#636366",
    placeholder: "#B4B4BA",
    inputBackground: "#FFFFFF",
    inputText: "#111113",
    inputBorder: "#5C5C5F",
    buttonPrimary: "#D35400",
    buttonSecondary: "#3A3A3C",
    buttonText: "#fff",
    cardBackground: "#FFFFFF",
    modalOverlay: "rgba(0, 0, 0, 0.45)",
    statusBar: "dark-content",
  },
};
